// 洪盛集藏 AI API · Cloudflare Workers
// Secrets: AI_API_KEY. Optional vars: AI_BASE_URL, AI_MODEL. Optional D1 binding: DB.
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json;charset=UTF-8"}})}
function intent(q){if(/版别|版式|字体|特征/.test(q))return"VARIETY_RESEARCH";if(/历史|年代|铸造|铸局|人物/.test(q))return"HISTORY_RESEARCH";if(/真伪|真假|鉴定/.test(q))return"AUTHENTICITY_ASSIST";if(/文献|论文|资料|出处/.test(q))return"DOCUMENT_RESEARCH";return"KNOWLEDGE_QA"}
const plans={VARIETY_RESEARCH:["实体识别","特征拆解","相似版别召回","文献证据比对","争议标记"],HISTORY_RESEARCH:["时代定位","人物/铸局关联","制度背景","史料交叉验证"],AUTHENTICITY_ASSIST:["图像特征提取","工艺特征对照","异常点提示","专业复核建议"],DOCUMENT_RESEARCH:["关键词扩展","文献召回","证据链整理","观点差异标注"],KNOWLEDGE_QA:["问题理解","知识召回","关系扩展","证据汇总"]};
async function ai(prompt,env){if(!env.AI_API_KEY)return null;const base=(env.AI_BASE_URL||"https://api.openai.com/v1").replace(/\/$/,"");const model=env.AI_MODEL||"gpt-4.1-mini";const r=await fetch(base+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+env.AI_API_KEY},body:JSON.stringify({model,messages:[{role:"system",content:"你是洪盛集藏AI钱币研究助手。只做知识研究辅助。必须区分事实、推断与争议；不提供确定性鉴定、买卖或投资建议。优先给出来源字段。"},{role:"user",content:prompt}],temperature:.2})});if(!r.ok)throw new Error("AI provider error "+r.status);const d=await r.json();return d?.choices?.[0]?.message?.content||null}
async function vision(body,env){const image=String(body?.image||"");const question=String(body?.question||"请研究这枚钱币").trim();if(!image.startsWith("data:image/"))return json({error:"请提供有效的钱币图片"},400);if(image.length>12000000)return json({error:"图片过大，请压缩后重试"},413);if(!env.AI_API_KEY)return json({status:"demo_mode",answer:"AI API尚未配置。当前仅完成图片接收与研究流程演示。",features:["铭文观察","图案结构","边齿观察","磨损特征","材质表现","待核验项"],disclaimer:"仅供收藏知识学习与研究交流，不构成鉴定、估值、交易或投资建议。"});const base=(env.AI_BASE_URL||"https://api.openai.com/v1").replace(/\/$/,"");const model=env.AI_MODEL||"gpt-4.1-mini";const prompt=question+"\n请严格按以下结构输出：1.观察事实；2.可能的类别/版式线索；3.需要核验的关键特征；4.证据与未知；5.下一步研究。不要给出确定性真伪、价格或交易建议。";try{const r=await fetch(base+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+env.AI_API_KEY},body:JSON.stringify({model,messages:[{role:"system",content:"你是洪盛集藏Vision AI钱币研究助手。只做图像观察和收藏知识研究。必须把观察事实、推断和未知分开；不能凭照片确定真伪、稀有度或市场价值。"},{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:image}}]}],temperature:.2})});if(!r.ok)throw new Error("AI provider error "+r.status);const d=await r.json();return json({status:"ok",version:"10.0.0",answer:d?.choices?.[0]?.message?.content||"AI未返回内容",features:["图像主体","铭文与字体","图案与版式","边缘/边齿","磨损与状态","待核验特征"],disclaimer:"视觉分析不能替代实物鉴定。涉及稀有版别或高价机会，请先核实来源、真伪与市场价值。"})}catch(e){return json({error:"AI视觉服务暂不可用"},502)}}
async function research(body,env){const q=String(body?.question||"").trim();if(!q)return json({error:"请输入研究问题"},400);const i=intent(q);let answer=null;try{answer=await ai("研究问题："+q+"\n请按：结论、证据、争议、下一步研究、来源建议 输出。",env)}catch(e){return json({status:"provider_error",message:"AI服务暂不可用"},502)}return json({status:"ok",version:"9.1.0",intent:i,question:q,plan:plans[i],answer:answer||"AI API尚未配置。当前返回结构化研究计划。",confidence:answer?"模型输出，仍需来源核验":"待真实知识库验证",disclaimer:"仅供收藏知识学习与研究交流，不构成鉴定、估值、交易或投资建议。"})}
async function coinSearch(q,env){if(!env.DB)return json({items:[],query:q,status:"knowledge_base_pending"});try{const like='%'+q.replace(/[\\%_]/g,'\\$&')+'%';const r=await env.DB.prepare("SELECT id,name,category,era,mint,variant,material,description FROM coins WHERE name LIKE ?1 ESCAPE '\\' OR variant LIKE ?1 ESCAPE '\\' OR category LIKE ?1 ESCAPE '\\' OR era LIKE ?1 ESCAPE '\\' LIMIT 30").bind(like).all();return json({status:"d1",query:q,items:r.results||[]})}catch(e){return json({status:"db_error",query:q,items:[],message:"知识库检索失败"},503)}}
async function marketSummary(env){if(!env.DB)return json({status:"seed_mode",sample_count:0,message:"D1尚未绑定，使用前端公开示例数据"});try{const r=await env.DB.prepare("SELECT COUNT(*) sample_count, MIN(price) low, MAX(price) high, AVG(price) average FROM market_records WHERE result_type='transaction'").first();return json({status:"d1",...r})}catch(e){return json({status:"db_error",message:"行情数据库暂不可用"},503)}}
export default {async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});const u=new URL(request.url);if(u.pathname==="/health")return json({ok:true,service:"hongsheng-jicang-api",version:"10.0.0",database:Boolean(env.DB),ai:Boolean(env.AI_API_KEY),vision:true});if(u.pathname==="/api/ai/research"&&request.method==="POST")return research(await request.json(),env);if(u.pathname==="/api/ai/vision"&&request.method==="POST")return vision(await request.json(),env);if(u.pathname==="/api/ai/chat"&&request.method==="POST"){const b=await request.json();let answer=null;try{answer=await ai(String(b?.message||b?.question||""),env)}catch(e){return json({error:"AI服务暂不可用"},502)}return json({status:"ok",answer:answer||"AI API尚未配置",disclaimer:"研究辅助用途"})}if(u.pathname==="/api/coins/search"){const q=String(u.searchParams.get("q")||"").trim();if(!q)return json({items:[],query:q,status:"empty_query"});return coinSearch(q,env)}if(u.pathname==="/api/news")return json({items:[],status:"source_connector_pending"});if(u.pathname==="/api/market/summary")return marketSummary(env);return json({service:"洪盛集藏 AI API",routes:["/health","/api/ai/chat","/api/ai/research","/api/ai/vision","/api/coins/search","/api/news","/api/market/summary"]})}};