// 洪盛集藏 AI API · Cloudflare Workers
// AI research + Vision + knowledge search. D1 is optional: without D1, the built-in verified seed remains searchable.
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json;charset=UTF-8"}})}
function intent(q){if(/版别|版式|字体|特征|边齿/.test(q))return"VARIETY_RESEARCH";if(/历史|年代|铸造|铸局|人物/.test(q))return"HISTORY_RESEARCH";if(/真伪|真假|鉴定/.test(q))return"AUTHENTICITY_ASSIST";if(/文献|论文|资料|出处|来源/.test(q))return"DOCUMENT_RESEARCH";if(/防诈|骗局|捡漏|诈骗|套路/.test(q))return"COLLECTION_SAFETY";return"KNOWLEDGE_QA"}
const plans={VARIETY_RESEARCH:["实体识别","特征拆解","相似版别召回","文献证据比对","争议标记"],HISTORY_RESEARCH:["时代定位","人物/铸局关联","制度背景","史料交叉验证"],AUTHENTICITY_ASSIST:["图像特征提取","工艺特征对照","异常点提示","专业复核建议"],DOCUMENT_RESEARCH:["关键词扩展","文献召回","证据链整理","观点差异标注"],COLLECTION_SAFETY:["识别诱导话术","核实来源","区分报价与成交","检查证据","形成风险清单"],KNOWLEDGE_QA:["问题理解","知识召回","关系扩展","证据汇总"]};
const SEED=[
{id:"coin-song-chongning-treasure",name:"崇宁重宝",category:"古钱币",era:"北宋",mint:"宋代铸钱体系",variant:"待按实物与文献进一步细分",material:"铜",description:"北宋钱币研究对象。研究可围绕钱文、书体、形制、铸造制度、时代背景及版别差异展开。",trust_level:"verified_research"},
{id:"coin-sun-yat-sen-1933",name:"1933孙中山像壹圆",category:"机制币",era:"民国",mint:"中国机制币体系",variant:"三鸟壹圆等相关版别需按具体实物确认",material:"银",description:"民国机制币研究对象。可从版式、图案、齿边、重量、直径、评级与公开拍卖记录等维度研究。",trust_level:"verified_research"},
{id:"coin-kiangnan-1900-72",name:"1900庚子江南省造七分二厘",category:"机制币",era:"清代",mint:"江南省造",variant:"七分二厘",material:"银",description:"清代地方机制币研究对象。研究可结合铸局、年份、面值、版式、评级和公开成交记录。",trust_level:"verified_research"},
{id:"coin-beiyang-dragon",name:"北洋龙机制币",category:"机制币",era:"清代",mint:"北洋相关铸造体系",variant:"不同年份与版式需分别建档",material:"银",description:"清代机制币研究主题。不同年份、面值和版式应拆分为独立研究实体。",trust_level:"community_view"},
{id:"topic-numis-dna",name:"Numis DNA 钱币数字特征",category:"研究主题",era:"跨时代",mint:"",variant:"文字/图案/边齿/尺寸/重量/材质/局部视觉特征",material:"",description:"将钱币可观察特征结构化，形成可检索的研究指纹，用于知识检索、相似对象比较和研究线索发现。",trust_level:"verified_research"}
];
async function ai(prompt,env){if(!env.AI_API_KEY)return null;const base=(env.AI_BASE_URL||"https://api.openai.com/v1").replace(/\/$/,"");const model=env.AI_MODEL||"gpt-4.1-mini";const r=await fetch(base+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+env.AI_API_KEY},body:JSON.stringify({model,messages:[{role:"system",content:"你是洪盛集藏AI钱币研究助手。只做知识研究辅助。必须区分事实、推断与争议；不提供确定性鉴定、买卖或投资建议。优先说明证据和来源。"},{role:"user",content:prompt}],temperature:.2})});if(!r.ok)throw new Error("AI provider error "+r.status);const d=await r.json();return d?.choices?.[0]?.message?.content||null}
async function vision(body,env){const image=String(body?.image||"");const question=String(body?.question||"请研究这枚钱币").trim();if(!image.startsWith("data:image/"))return json({error:"请提供有效的钱币图片"},400);if(image.length>12000000)return json({error:"图片过大，请压缩后重试"},413);if(!env.AI_API_KEY)return json({status:"demo_mode",answer:"AI API尚未配置。当前完成图片接收与研究流程演示。",features:["铭文观察","图案结构","边齿观察","磨损特征","材质表现","待核验项"],disclaimer:"仅供收藏知识学习与研究交流，不构成鉴定、估值、交易或投资建议。"});const base=(env.AI_BASE_URL||"https://api.openai.com/v1").replace(/\/$/,"");const model=env.AI_MODEL||"gpt-4.1-mini";const prompt=question+"\n请严格按以下结构输出：1.观察事实；2.可能的类别/版式线索；3.需要核验的关键特征；4.证据与未知；5.下一步研究。不要给出确定性真伪、价格或交易建议。";try{const r=await fetch(base+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+env.AI_API_KEY},body:JSON.stringify({model,messages:[{role:"system",content:"你是洪盛集藏Vision AI钱币研究助手。只做图像观察和收藏知识研究。必须把观察事实、推断和未知分开；不能凭照片确定真伪、稀有度或市场价值。"},{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:image}}]}],temperature:.2})});if(!r.ok)throw new Error("AI provider error "+r.status);const d=await r.json();return json({status:"ok",version:"11.0.0",answer:d?.choices?.[0]?.message?.content||"AI未返回内容",features:["图像主体","铭文与字体","图案与版式","边缘/边齿","磨损与状态","待核验特征"],disclaimer:"视觉分析不能替代实物鉴定。涉及稀有版别或高价机会，请先核实来源、真伪与市场价值。"})}catch(e){return json({error:"AI视觉服务暂不可用"},502)}}
async function research(body,env){const q=String(body?.question||"").trim();if(!q)return json({error:"请输入研究问题"},400);const i=intent(q);let answer=null;try{answer=await ai("研究问题："+q+"\n请按：结论、证据、争议、下一步研究、来源建议 输出。",env)}catch(e){return json({status:"provider_error",message:"AI服务暂不可用"},502)}return json({status:"ok",version:"11.0.0",intent:i,question:q,plan:plans[i],answer:answer||"AI API尚未配置。当前返回结构化研究计划，并可使用内置知识种子进行检索。",confidence:answer?"模型输出，仍需来源核验":"待知识库与来源进一步验证",disclaimer:"仅供收藏知识学习与研究交流，不构成鉴定、估值、交易或投资建议。"})}
function textMatch(item,q){const s=[item.name,item.category,item.era,item.mint,item.variant,item.material,item.description].join(" ").toLowerCase();return !q||s.includes(q.toLowerCase())}
async function coinSearch(q,env){if(env.DB){try{const like="%"+q.replace(/[\\%_]/g,"\\$&")+"%";const r=await env.DB.prepare("SELECT id,name,category,era,mint,variant,material,description FROM coins WHERE name LIKE ?1 ESCAPE '\\' OR variant LIKE ?1 ESCAPE '\\' OR category LIKE ?1 ESCAPE '\\' OR era LIKE ?1 ESCAPE '\\' LIMIT 30").bind(like).all();if((r.results||[]).length)return json({status:"d1",query:q,items:r.results})}catch(e){/* fallback to seed */}}return json({status:"seed_mode",query:q,items:SEED.filter(x=>textMatch(x,q)).slice(0,30),total:SEED.filter(x=>textMatch(x,q)).length})}
async function marketSummary(env){if(!env.DB)return json({status:"seed_mode",sample_count:0,message:"D1尚未绑定，使用前端公开示例数据"});try{const r=await env.DB.prepare("SELECT COUNT(*) sample_count, MIN(price) low, MAX(price) high, AVG(price) average FROM market_records WHERE result_type='transaction'").first();return json({status:"d1",...r})}catch(e){return json({status:"db_error",message:"行情数据库暂不可用"},503)}}
export default {async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});const u=new URL(request.url);if(u.pathname==="/health")return json({ok:true,service:"hongsheng-jicang-api",version:"11.0.0",database:Boolean(env.DB),ai:Boolean(env.AI_API_KEY),vision:true,knowledge_seed:SEED.length});if(u.pathname==="/api/ai/research"&&request.method==="POST")return research(await request.json(),env);if(u.pathname==="/api/ai/vision"&&request.method==="POST")return vision(await request.json(),env);if(u.pathname==="/api/ai/chat"&&request.method==="POST"){const b=await request.json();let answer=null;try{answer=await ai(String(b?.message||b?.question||""),env)}catch(e){return json({error:"AI服务暂不可用"},502)}return json({status:"ok",answer:answer||"AI API尚未配置",disclaimer:"研究辅助用途"})}if(u.pathname==="/api/coins/search"){const q=String(u.searchParams.get("q")||"").trim();return coinSearch(q,env)}if(u.pathname==="/api/news")return json({items:[],status:"source_connector_pending"});if(u.pathname==="/api/market/summary")return marketSummary(env);return json({service:"洪盛集藏 AI API",routes:["/health","/api/ai/chat","/api/ai/research","/api/ai/vision","/api/coins/search","/api/news","/api/market/summary"]})}};